
# Unit 3 Sections 12 and 13 lesson
> Developing and Writing Procedures Lesson

- title: Unit 3 Sections 12-13
- toc: true
- badges: false
- categories: [3.12-3.13]
- Libraries
A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations.
These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.

A library may also contain documentation, configuration data, message templates, classes, and values, etc.
Why are libraries important?
Using Libraries makes Python Programming simpler and convenient for the programmer.
One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs.
Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.
A few libraries that simplify coding processes:

Pillow allows you to work with images.
Tensor Flow helps with data automation and monitors performance.
Matplotlib allows you to make 2D graphs and plots.

The AP Exam Refrence Sheet itself is a library!

# Hacks

Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

API’s
An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used.
An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.
Activity: Walkthrough with NumPy
Install NumPy on VSCode:
Open New Terminal In VSCode:
pip3 install --upgrade pip
pip install numpy
REMEMBER: When running library code cells use Python Interpreter Conda (Version 3.9.12)

In [1]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


# Random Values
Random number generation (RNG) produces a random number (crazy right?)
This means that a procedure with RNG can return different values even if the parameters (inputs) do not change

CollegeBoard uses RANDOM(A, B), to return an integer between integers A and B.
RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10

In Python, this would be random.randint(A, B), after importing Python's "random" library (import random)

JavaScript's works a little differently, with Math.random() returning a value between 0 and 1.

To match Python and CollegeBoard, you could make a procedure like this

In [12]:
import random 

def Dice(n):
    sum = 0
    while n !=0:
        sum = sum + random.randint(1,6)
        n = n - 1
    return sum

Dice(5)

13